import React, { useEffect, useRef, useState } from 'react';
import { Play, Trophy } from 'lucide-react';
import { StarCatcherResult } from '../../types';
import { useI18n } from '../../i18n/context';
import { EXPERIMENT_TIMINGS } from '../../config/runtime';
import { celebrateTaskCompletion } from '../../utils/celebration';

interface Props { onGameEnd?: (result: StarCatcherResult) => void; }
type Point = StarCatcherResult['path'][number];
const DURATION_MS = EXPERIMENT_TIMINGS.starCatcherMs;
const SAMPLE_MS = 1000 / 30;
const TARGET_RADIUS = 20;

function drawLine(ctx: CanvasRenderingContext2D, points: Point[], color: string, width: number, alpha = 1, target = false) {
  if (points.length < 2) return;
  ctx.save(); ctx.globalAlpha = alpha; ctx.strokeStyle = color; ctx.lineWidth = width; ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.beginPath();
  points.forEach((point, index) => { const x = target ? point.targetX : point.x; const y = target ? point.targetY : point.y; index ? ctx.lineTo(x, y) : ctx.moveTo(x, y); }); ctx.stroke(); ctx.restore();
}

export const StarCatcherGame: React.FC<Props> = ({ onGameEnd }) => {
  const { locale } = useI18n(); const zh = locale === 'zh'; const canvasRef = useRef<HTMLCanvasElement>(null); const frameRef = useRef(0); const startRef = useRef(0); const lastSampleRef = useRef(0); const playerRef = useRef({ x: 300, y: 280 }); const boundsRef = useRef({ width: 600, height: 380 }); const rawRef = useRef<Point[]>([]); const playerTrailRef = useRef<Point[]>([]); const targetTrailRef = useRef<Point[]>([]); const timerRef = useRef<number | null>(null);
  const [playing, setPlaying] = useState(false); const [seconds, setSeconds] = useState(DURATION_MS / 1000); const [result, setResult] = useState<StarCatcherResult | null>(null); const [showResult, setShowResult] = useState(false);
  const targetAt = (elapsed: number, width = boundsRef.current.width, height = boundsRef.current.height) => ({ x: width * (0.5 + .39 * Math.sin(2 * Math.PI * elapsed / 4700)), y: height * (0.5 + .32 * Math.sin(2 * Math.PI * elapsed / 3100 + Math.PI / 2)) });
  const stop = () => {
    if (!playing) return; setPlaying(false); cancelAnimationFrame(frameRef.current); const ended = Date.now(); const path = rawRef.current; const distances = path.map(p => Math.hypot(p.x - p.targetX, p.y - p.targetY)); const rmse = distances.length ? Math.sqrt(distances.reduce((a, b) => a + b * b, 0) / distances.length) : 0; const onTarget = distances.length ? distances.filter(d => d <= TARGET_RADIUS).length * 100 / distances.length : 0;
    let phaseLagMs = 0; let best = Infinity; for (let lag = -600; lag <= 600; lag += 40) { const error = path.reduce((sum, point) => { const t = targetAt(point.timestamp - startRef.current + lag); return sum + Math.hypot(point.x - t.x, point.y - t.y) ** 2; }, 0); if (error < best) { best = error; phaseLagMs = lag; } }
    const next: StarCatcherResult = { id: `GAME-${ended.toString(36).toUpperCase()}`, timestamp: ended, taskVersion: 'lissajous-tracking-v3', score: Math.round(Math.max(0, 100 - rmse)), combo: 0, starsCollected: 0, totalStars: 0, hitRate: Number(onTarget.toFixed(1)), averageReactionMs: 0, controlAccuracy: Math.round(onTarget), movementSmoothness: 0, fineMotorScore: Math.round(Math.max(0, 100 - rmse)), durationSec: Number(((ended - startRef.current) / 1000).toFixed(2)), trackingRMSEPx: Number(rmse.toFixed(2)), onTargetPercent: Number(onTarget.toFixed(2)), phaseLagMs, noGoEntries: 0, noGoDwellMs: 0, path };
    setSeconds(0); setResult(next); celebrateTaskCompletion(); if ('vibrate' in navigator) navigator.vibrate?.([40, 30, 70]); onGameEnd?.(next); timerRef.current = window.setTimeout(() => setShowResult(true), 750);
  };
  const start = () => { const canvas = canvasRef.current; const width = canvas?.clientWidth || 600; const height = canvas?.clientHeight || 380; boundsRef.current = { width, height }; playerRef.current = { x: width / 2, y: height * .82 }; rawRef.current = []; playerTrailRef.current = []; targetTrailRef.current = []; startRef.current = Date.now(); lastSampleRef.current = 0; if (timerRef.current) window.clearTimeout(timerRef.current); setSeconds(DURATION_MS / 1000); setResult(null); setShowResult(false); setPlaying(true); };
  useEffect(() => () => { cancelAnimationFrame(frameRef.current); if (timerRef.current) window.clearTimeout(timerRef.current); }, []);
  useEffect(() => { const canvas = canvasRef.current; const ctx = canvas?.getContext('2d'); if (!canvas || !ctx) return; const stars = Array.from({ length: 28 }, (_, i) => ({ x: ((i * 83) % 997) / 997, y: ((i * 151) % 991) / 991, r: .5 + i % 3 * .3 })); const render = () => { const dpr = window.devicePixelRatio || 1; const width = canvas.clientWidth || 600; const height = canvas.clientHeight || 380; boundsRef.current = { width, height }; if (canvas.width !== width * dpr || canvas.height !== height * dpr) { canvas.width = width * dpr; canvas.height = height * dpr; } const now = Date.now(); const elapsed = Math.max(0, now - startRef.current); const target = targetAt(elapsed, width, height); if (playing && now - lastSampleRef.current >= SAMPLE_MS) { lastSampleRef.current = now; const point: Point = { ...playerRef.current, timestamp: now, targetX: target.x, targetY: target.y, inNoGo: false }; rawRef.current.push(point); playerTrailRef.current.push(point); targetTrailRef.current.push({ ...point, x: target.x, y: target.y }); playerTrailRef.current = playerTrailRef.current.filter(p => now - p.timestamp <= 700); targetTrailRef.current = targetTrailRef.current.filter(p => now - p.timestamp <= 420); }
      ctx.save(); ctx.scale(dpr, dpr); const bg = ctx.createLinearGradient(0, 0, width, height); bg.addColorStop(0, '#13213e'); bg.addColorStop(1, '#020617'); ctx.fillStyle = bg; ctx.fillRect(0, 0, width, height); ctx.fillStyle = 'rgba(226,232,240,.25)'; stars.forEach(s => { ctx.beginPath(); ctx.arc(s.x * width, s.y * height, s.r, 0, Math.PI * 2); ctx.fill(); }); drawLine(ctx, targetTrailRef.current, '#fbbf24', 1.5, .42, true); drawLine(ctx, playerTrailRef.current, '#38bdf8', 3.2, .66); const halo = ctx.createRadialGradient(target.x, target.y, 2, target.x, target.y, 34); halo.addColorStop(0, '#fff7ae'); halo.addColorStop(.3, 'rgba(250,204,21,.85)'); halo.addColorStop(1, 'rgba(250,204,21,0)'); ctx.fillStyle = halo; ctx.beginPath(); ctx.arc(target.x, target.y, 34, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#fde68a'; ctx.beginPath(); ctx.arc(target.x, target.y, TARGET_RADIUS, 0, Math.PI * 2); ctx.fill(); const p = playerRef.current; const playerGlow = ctx.createRadialGradient(p.x, p.y, 2, p.x, p.y, 25); playerGlow.addColorStop(0, '#cffafe'); playerGlow.addColorStop(.35, 'rgba(34,211,238,.8)'); playerGlow.addColorStop(1, 'rgba(34,211,238,0)'); ctx.fillStyle = playerGlow; ctx.beginPath(); ctx.arc(p.x, p.y, 25, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#cffafe'; ctx.beginPath(); ctx.arc(p.x, p.y, 8, 0, Math.PI * 2); ctx.fill(); ctx.restore(); if (playing) { if (elapsed >= DURATION_MS) stop(); else frameRef.current = requestAnimationFrame(render); } }; render(); return () => cancelAnimationFrame(frameRef.current); }, [playing]);
  useEffect(() => { if (!playing) return; const interval = window.setInterval(() => setSeconds(Math.max(0, Math.ceil((DURATION_MS - (Date.now() - startRef.current)) / 1000))), 120); return () => window.clearInterval(interval); }, [playing]);
  const move = (event: React.PointerEvent<HTMLCanvasElement>) => { if (!playing) return; const rect = event.currentTarget.getBoundingClientRect(); playerRef.current = { x: event.clientX - rect.left, y: event.clientY - rect.top }; };
  const metric = (name: string, value: string) => <div className="rounded-xl border border-slate-200 bg-slate-50 p-3"><div className="text-xs text-slate-400">{name}</div><div className="mt-1 font-mono font-bold">{value}</div></div>;
  return <div className="max-w-4xl mx-auto space-y-5"><header className="bg-white p-6 rounded-2xl border border-slate-200"><span className="text-xs font-mono text-cyan-700">{zh ? '标准化追踪任务 · 固定轨迹 · Lissajous 2:3' : 'Standardized tracking · fixed path · Lissajous 2:3'}</span><h2 className="text-2xl font-bold mt-1">{zh ? 'Star Catcher 轨迹追踪' : 'Star Catcher Trajectory Tracking'}</h2><p className="text-sm text-slate-500 mt-2">{zh ? `持续跟随黄色目标，尽可能让控制点贴近目标。` : 'Keep your cyan control point as close to the yellow target as possible.'}</p></header><section className="bg-white p-5 rounded-2xl border border-slate-200"><div className="mb-3 flex justify-between text-sm font-mono"><span>{playing ? (zh ? '追踪中' : 'Tracking') : result && !showResult ? (zh ? '测量完成' : 'Tracking complete') : (zh ? '准备开始' : 'Ready')}</span><span>{zh ? '剩余' : 'Remaining'} {seconds}s</span></div><canvas ref={canvasRef} onPointerMove={move} className="w-full h-[380px] rounded-xl bg-slate-950 touch-none" />{!playing && <div className="mt-4 text-center"><button type="button" onClick={start} className="inline-flex items-center gap-2 rounded-xl bg-cyan-600 px-6 py-3 text-white font-semibold"><Play className="w-4 h-4" />{result ? (zh ? '再次测试' : 'Retest') : (zh ? '开始追踪' : 'Start tracking')}</button></div>}</section>{showResult && result && <section className="bg-white p-5 rounded-2xl border border-slate-200 animate-in fade-in duration-300"><div className="flex gap-2 items-center font-bold"><Trophy className="w-5 h-5 text-amber-500" />{zh ? '轨迹对比' : 'Tracking Path'}</div><PathCanvas result={result} zh={zh} /><div className="mt-4 grid grid-cols-2 sm:grid-cols-4 gap-3 text-sm">{metric(zh ? '追踪误差 RMSE' : 'Tracking RMSE', `${result.trackingRMSEPx}px`)}{metric(zh ? '在靶时间' : 'On-target', `${result.onTargetPercent}%`)}{metric(zh ? '响应滞后' : 'Phase lag', `${result.phaseLagMs}ms`)}{metric(zh ? '任务时长' : 'Duration', `${result.durationSec}s`)}</div></section>}</div>;
};

const PathCanvas: React.FC<{ result: StarCatcherResult; zh: boolean }> = ({ result, zh }) => { const ref = useRef<HTMLCanvasElement>(null); useEffect(() => { const canvas = ref.current; const ctx = canvas?.getContext('2d'); if (!canvas || !ctx) return; const width = canvas.clientWidth || 680; const height = canvas.clientHeight || 300; const dpr = window.devicePixelRatio || 1; canvas.width = width * dpr; canvas.height = height * dpr; ctx.scale(dpr, dpr); ctx.fillStyle = '#0f172a'; ctx.fillRect(0, 0, width, height); drawLine(ctx, result.path, '#fbbf24', 1.6, .9, true); drawLine(ctx, result.path, '#22d3ee', 2.5, .9); ctx.font = '12px system-ui'; ctx.fillStyle = '#fbbf24'; ctx.fillText(zh ? '黄 · 目标' : 'Gold · Target', 16, 23); ctx.fillStyle = '#22d3ee'; ctx.fillText(zh ? '蓝 · 你的轨迹' : 'Cyan · You', 115, 23); }, [result, zh]); return <canvas ref={ref} className="mt-4 h-[300px] w-full rounded-xl bg-slate-950" />; };
